apiVersion: v1
kind: Service
metadata:
  name: ri-agent
  namespace: ri-agent
spec:
  type: ClusterIP
  selector:
    app: ri-agent
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
